### ISSUE TITLE
I have no idea what caused this crash

### ISSUE THREAD

**Issue by SwornGamer** [HxCKDMS/HxCEnchants#1]
I just started up a new modpack when I added this mod and I broke a leaf block and it suddenly crashed.

---- Minecraft Crash Report ----
// Why is it breaking :(

Time: 4/28/15 2:10 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
    at HxCKDMS.HxCEnchants.Handlers.ToolEventHandler.onHarvestBlocks(ToolEventHandler.java:195)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_556_ToolEventHandler_onHarvestBlocks_HarvestDropsEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
    at net.minecraftforge.event.ForgeEventFactory.fireBlockHarvesting(ForgeEventFactory.java:155)
    at net.minecraft.block.Block.func_149690_a(Block.java:656)
    at net.minecraft.block.BlockLeaves.func_149690_a(BlockLeaves.java:241)
    at net.minecraft.block.Block.func_149697_b(Block.java:648)
    at net.minecraft.block.Block.func_149636_a(Block.java:974)
    at net.minecraft.block.BlockLeaves.func_149636_a(BlockLeaves.java:254)
    at net.minecraft.server.management.ItemInWorldManager.func_73084_b(ItemInWorldManager.java:299)
    at net.minecraft.server.management.ItemInWorldManager.func_73075_a(ItemInWorldManager.java:107)
    at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java:204)
    at net.minecraft.world.World.func_72866_a(World.java:2070)
    at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
    at net.minecraft.world.World.func_72870_g(World.java:2034)
    at net.minecraft.world.World.func_72939_s(World.java:1887)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by DrZed** [comment]
I'll look into it very soon

**Comment by DrZed** [comment]
For the mean time disable AutoSmelt enchant in the configs or FlameTouch I forgot what it's called in the config XD

**Comment by SwornGamer** [comment]
I had it disabled because I don't like auto-smelt and that crashed happened anyways

**Comment by DrZed** [comment]
OOPS
I forgot to do something
pushing update in a few minutes

**Comment by DrZed** [comment]
http://puu.sh/hD6fQ.jar

**Comment by DrZed** [comment]
That's the latest version tell me if it fixes it

**Comment by DrZed** [comment]
See unlike the other Configs to disable enchants I forgot to add  If(Config.AutoSmelt Enabled) {check for autosmelt} I fixed that

**Comment by SwornGamer** [comment]
That has done it.

**Comment by DrZed** [comment]
Thank you for the feedback would you like to be added to the HxC Debuggers Group ?_? You get [HxCHelper] beside your name in the game (I won't ask you to do anything It's just you helped me realize I did something stupid when tired coding xD)

**Comment by SwornGamer** [comment]
Sure, That sounds fantastic I'm glad that that I could help you, If you need my minecraft name it's the same as the git hub which I just changed to fit my new changed MC name.

**Comment by DrZed** [comment]
Done! Next time you join a server you'll have [HxCHelper] next to your name :3
